# Generated by Django 4.0.3 on 2022-05-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ph_pro',
            field=models.BigIntegerField(default='0905082929'),
        ),
    ]
