# Generated by Django 4.0.3 on 2022-05-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_nur_prof_billingdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cate',
        ),
        migrations.AddField(
            model_name='service',
            name='nur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.nursery'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='billingdetails',
        ),
    ]
