# Generated by Django 4.0.3 on 2022-05-25 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_service_cate_service_nur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursery',
            name='cate',
        ),
        migrations.AddField(
            model_name='service',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
