# Generated by Django 4.0.3 on 2022-05-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_nursery_cate_service_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cate',
        ),
        migrations.AddField(
            model_name='nursery',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.category'),
        ),
    ]
