# Generated by Django 4.0.3 on 2022-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_billingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
