# Generated by Django 4.0.3 on 2022-05-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
