# Generated by Django 4.0.3 on 2022-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tips', models.TextField()),
                ('plant', models.CharField(max_length=50)),
                ('more_info', models.CharField(default=None, max_length=50)),
                ('added_on', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
